hl.workspace_rule({workspace = 1, monitor = "desc:LG Display 0x06E2", default = true, persistent = true})
hl.workspace_rule({workspace = 2, monitor = "desc:LG Display 0x06E2", persistent = true})
hl.workspace_rule({workspace = 3, monitor = "desc:LG Display 0x06E2", persistent = true})
hl.workspace_rule({workspace = 4, monitor = "desc:LG Display 0x06E2", persistent = true})
hl.workspace_rule({workspace = 5, monitor = "desc:LG Display 0x06E2", persistent = true})
hl.workspace_rule({workspace = 6, monitor = "desc:LG Display 0x06E2", persistent = true})
hl.workspace_rule({workspace = 7, monitor = "desc:LG Display 0x06E2", persistent = true})
hl.workspace_rule({workspace = 8, monitor = "desc:LG Display 0x06E2", persistent = true})
hl.workspace_rule({workspace = 9, monitor = "desc:LG Display 0x06E2", persistent = true})
hl.workspace_rule({workspace = 10, monitor = "desc:LG Display 0x06E2", persistent = true})

hl.workspace_rule({workspace = 11, monitor = "HDMI-A-1", default = true, persistent = true})
hl.workspace_rule({workspace = 12, monitor = "HDMI-A-1", persistent = true})
hl.workspace_rule({workspace = 13, monitor = "HDMI-A-1", persistent = true})
hl.workspace_rule({workspace = 14, monitor = "HDMI-A-1", persistent = true})
hl.workspace_rule({workspace = 15, monitor = "HDMI-A-1", persistent = true})
hl.workspace_rule({workspace = 16, monitor = "HDMI-A-1", persistent = true})
hl.workspace_rule({workspace = 17, monitor = "HDMI-A-1", persistent = true})
hl.workspace_rule({workspace = 18, monitor = "HDMI-A-1", persistent = true})
hl.workspace_rule({workspace = 19, monitor = "HDMI-A-1", persistent = true})
hl.workspace_rule({workspace = 20, monitor = "HDMI-A-1", persistent = true})

hl.workspace_rule({workspace = 21, monitor = "DP-1", default = true, persistent =true})
hl.workspace_rule({workspace = 22, monitor = "DP-1", persistent = true})
hl.workspace_rule({workspace = 23, monitor = "DP-1", persistent = true})
hl.workspace_rule({workspace = 24, monitor = "DP-1", persistent = true})
hl.workspace_rule({workspace = 25, monitor = "DP-1", persistent = true})
hl.workspace_rule({workspace = 26, monitor = "DP-1", persistent = true})
hl.workspace_rule({workspace = 27, monitor = "DP-1", persistent = true})
hl.workspace_rule({workspace = 28, monitor = "DP-1", persistent = true})
hl.workspace_rule({workspace = 29, monitor = "DP-1", persistent = true})
hl.workspace_rule({workspace = 30, monitor = "DP-1", persistent = true})
