	--use { 'antoinemadec/FixCursorHold.nvim' }
	--use { 'windwp/nvim-autopairs' }
	--use { 'nvim-neotest/neotest-python' }
	--use { 'glacambre/firenvim', run = function() vim.fn['firenvim#install'](0) end }
	--use { 'dstein64/vim-startuptime' }
	--use { 'itchyny/vim-gitbranch'}
	--use { 'hrsh7th/cmp-nvim-lsp' }
	--use { 'hrsh7th/cmp-buffer' }
	--use { 'hrsh7th/cmp-path' }
	--use { 'hrsh7th/cmp-cmdline' }
	--use { 'hrsh7th/cmp-nvim-lsp-signature-help' }
	--use { 'saadparwaiz1/cmp_luasnip' }
	--use { 'L3MON4D3/LuaSnip' }
	--use { 'onsails/lspkind-nvim' }
	--use { 'folke/neodev.nvim' }
	--use { 'neovim/nvim-lspconfig' }
	--use { 'williamboman/mason.nvim' }
	--use { 'williamboman/mason-lspconfig.nvim' }

