layerrule {
	name = rofi
	match:namespace = rofi
	blur = on
}

layerrule {
	name = nwg-drawer
	match:namespace = nwg-drawer
	blur = on
}

layerrule {
	name = waybar
	match:namespace = waybar
	blur = on
}

layerrule {
	name = swaync-control-center
	match:namespace = swaync-control-center
	blur = on
}


layerrule {
	name = swaync-notification-window
	match:namespace = swaync-notification-window
	blur = off
}

layerrule {
	name = selection
	match:namespace = selection
	no_anim = on
	blur = off
}
