# set cursor theme
exec-once = hyprctl setcursor Bibata-Modern-Ice 30

# set dbus env for XDG PORTAL
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP DISPLAY

# wallpaper and gtk settings
exec-once = systemd-cat -t waypaper waypaper --restore
exec-once = systemd-cat -t nwg-look nwg-look -a

# tray applets
exec-once = systemd-cat -t nm-applet nm-applet
exec-once = systemd-cat -t blueman-applet blueman-applet
exec-once = systemd-cat -t ctray ctray
exec-once = systemd-cat -t g15pc g15pc --tray

# bar/pannel
exec-once = systemd-cat -t waybar waybar

# notification center
# exec-once = env VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json swaync
exec-once = systemd-cat -t swaync swaync

exec-once = systemd-cat -t hypridle hypridle
exec-once = systemd-cat -t wljoywake wljoywake

# dbus file manager
exec-once = systemd-cat -t dbusfm dbusfm

# mail stuff
exec-once = systemd-cat -t goimapnotify goimapnotify -conf ~/.config/imapnotify/gmail.yaml

# clipboard history
exec-once = systemd-cat -t wl-paste wl-paste --type text --watch cliphist store

# touchpad gestures
exec-once = systemd-cat -t libinput-gestures libinput-gestures

# polkit auth agent
exec-once = systemd-cat -t polkit-gnome /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# exec-once = systemd-cat -t rbw-agent rbw-agent --no-daemonize
